### ISSUE TITLE
Language choice?

### ISSUE THREAD

**Issue by fetis** [entropic-dev/entropic#120]
Why it's all in Javascript not in Typescript? It would be much easier to develop registry in TypeScript.

**Comment by chrisdickinson** [comment]
Given the time frame we were working in, and the [first value listed here](https://github.com/entropic-dev/entropic/tree/master/docs#assumptions--decisions--the-chem-in-the-golems-head) – "do the dumbest thing that works, then iterate" – we picked the tool that would let us develop entropic most expediently. That is to say: vanilla JavaScript.

In any case, over time we'll iterate. It's entirely possible we end up at TypeScript, if it's worthwhile to head that direction & enough maintainers want to. For the time being, though, we're a JavaScript codebase.

I appreciate your interest in the project – you wouldn't have said anything if you hadn't been looking at contributing, I assume! As a heads up, opening an issue in a project questioning fundamental language choices in a project generally reads kind of rude, even if the other language is pretty similar / you perceive it has advantages. I'm sure this was not your intent, though!

**Comment by fetis** [comment]
@chrisdickinson never meant to be rude. I develop for years on TS and I see only benefits. I thought that your choice was based to stay independent from current registry. Does it fit in "dumbest thing that works"? I dunno.

**Comment by viktor-ku** [comment]
> Given the time frame we were working in, and the first value listed here – "do the dumbest thing that works, then iterate" – we picked the tool that would let us develop entropic most expediently. That is to say: vanilla JavaScript.

Pretty much what I've heard over and over and over in every project I am in. Always the same story. Always ends up rewriring the whole thing to ts just because vanilla project becomes read-only.

Not to be rude. I understand both positions.

**Comment by fetis** [comment]
I think this will be less painful right now when the code base is small.

What we can do is to run .js files under the TS and step-by-step introduce classes and interfaces, at the end completely replace them by .ts only.
