### ISSUE TITLE
Postgres host for test environment

### ISSUE THREAD

**Issue by olingern** [entropic-dev/entropic#133]
I noticed this error when I pushed #132. ~I'm guessing this is due to hosted databases actually costing money. Maybe a charitable, large cloud service could help?~

```
You must set up a .env file with "EXTERNAL_HOST" set to run this migration.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! entropic-registry@0.0.1 migrate: `PGUSER=postgres PGDATABASE=entropic_${NODE_ENV:-dev} db-migrate up --config db-migrate.json --env entropic`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the entropic-registry@0.0.1 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-06-04T00_53_36_968Z-debug.log
npm ERR! Test failed.  See above for more details.
Exited with code 1
```

**Comment by chrisdickinson** [comment]
Ah! This is actually because one of our migrations creates the initial `host` row so we can create `legacy@<current host>` and `abadonware@<current host>` namespaces. We derive the initial hostname from the value of `EXTERNAL_HOST`.

**Comment by olingern** [comment]
I see. I looked at the test config and there is indeed a postres instance there. :thinking: 

Perhaps, we need to have a `test.env` that aliases the postgres instance since the dev environment's `localhost` address isn't valid on CircleCI?

**Comment by chrisdickinson** [comment]
Oh! that's perfect.

**Comment by chrisdickinson** [comment]
(Some background: this was initially failing because CircleCI is configured not to send env vars in for jobs running as a result of a fork. Right now we don't have any sensitive env vars – we just set `EXTERNAL_HOST` to `http://localhost:3000`, so we could change that setting. That might change in the future, though, so if changing the `circleci/config.yml` works we should definitely do that.)

**Comment by zacanger** [comment]
I believe I fixed this in my most recently mergeed PR. @olingern are you up to date with master?

**Comment by olingern** [comment]
@zacanger this is different. This is specifically for the CircleCI build

**Comment by zacanger** [comment]
Yep, I was having issues with that until I added these env vars to the circle config: `run: PGHOST=localhost EXTERNAL_HOST=http://localhost:3000 npm test`. Now builds are passing just fine. I believe the rest of them are handled in services/registry/package.json.

**Comment by olingern** [comment]
I see. That probably does fix things, but I glossed over that. I think it's better form to be explicit in how environment variables are set and in what container. For example, prefixing `npm test` with `PG_HOST` I'm not sure if that environment variable is set on the postgres container _and_ the node container.

I can drop my `.circleci/config.yml` commits though if that's desired.

**Comment by zacanger** [comment]
That's up to you and @chrisdickinson! I just didn't want you to be putting in extra effort if you didn't have to

**Comment by olingern** [comment]
@zacanger thanks for the comments / fix! Going to close this as it's not an issue anymore
