### ISSUE TITLE
Why stop at package management?

### ISSUE THREAD

**Issue by AlexLeung** [entropic-dev/entropic#137]
Someone needs to create a decentralized platform that ideally solves all the following problems in one fell swoop:
1. package hosting
1. source repository hosting
1. creating greater incentives for people to contribute to open source
   1. a more accurate way of determining the value added by a contributor to a project than activity count
   1. open source contributors compensated relative to the value they add
1. decentralized governance of open source projects

Anyone who finds this topic interesting message me at alex.l.leung@gmail.com

**Comment by olingern** [comment]
I think there are a lot of possibilities. To me, getting something that works in the hands of people and letting users give feedback on pain points / desired features is more important than a grand vision that not or may not change.

**Comment by olingern** [comment]
I’m an arch user and I’ve grown to enjoy package installation via yay. 

pacman is the official package manager with Arch, but yay has much better ergonomics IMO.

So, having an open api allows anyone to develop a cli. I could easily see there being a yarn v2 plugin for this.

**Comment by jackallnutt** [comment]
There's the [ForgeFed](https://notabug.org/peers/forgefed) project which is attempting to create federated protocol for VCS systems based on ActivityPub (which is the protocol behind Mastodon, PixelFed and PeerTube).

**Comment by chrisdickinson** [comment]
Entropic will stop at package management for the foreseeable future. The founding maintainers have experience with this problem, and we perceive that the need to solve it (& solve it well) is pressing.

It may be that we find that Entropic is useful in situations we hadn't foreseen. However, until Entropic has achieved its original goal of making federated package management easy to set up & participate in, we should stay on target.
