### ISSUE TITLE
Docker external network issue

### ISSUE THREAD

**Issue by olingern** [entropic-dev/entropic#145]
### Description
I'm currently receiving this error when running `docker-compose up`:
<br/>
![DeepinScreenshot_select-area_20190605081005](https://user-images.githubusercontent.com/1470297/58919544-71149180-8769-11e9-9461-5cf25a4d4c5f.png)

<br/>
Looking at the [Docker documentation](https://docs.docker.com/compose/networking/), I'm not sure why the `entropic` network would be considered "pre-existing"

> If you want your containers to join a pre-existing network, use the external option:

Can anyone reproduce?

_note: setting `external` to `false` does fix this for me._
___

### System details:

**OS**: Arch Linux x86_64 
**docker**: 18.09.6-ce, build 481bc77156
**docker-compose**: 1.24.0

**Comment by olingern** [comment]
ping @zacanger :bowing_man: 

I saw you set this up in #119

**Comment by toddself** [comment]
I ran into this as well and just did `docker network create entropic`. It would be nice if it did it automatically though!

**Comment by zacanger** [comment]
Yep, just do `npm start`, I should've documented that, sorry! `npm start` runs [this script](https://github.com/entropic-dev/entropic/blob/master/misc/start.sh) which creates the network if it doesn't already exist.

**Comment by olingern** [comment]
Ah, [I see](https://github.com/entropic-dev/entropic/blob/master/package.json#L35).
`start": "./misc/start.sh`

Usually when I see a `docker-compose.yml` I take a glance and then `docker-compose up -d`. My only criticisms of the `npm start` is that I can't daemonize and it's a bit hidden. There could be users who don't read the README and open this issue again in the future.

I'm not super hip to external docker networking. Is there an advantage to having the startup script handle it vs letting docker-compose create it automatically?

Thanks for setting this up, by the way!

**Comment by zacanger** [comment]
The reason I had that set up as an external network is because I was initially using https://github.com/jwilder/nginx-proxy so I could hit the registry at `entropic.local` rather than `localhost:3000`, but decided that was probably assuming too much about what other users would want to do, so I took it out. It would've made sense to remove the external network.
