### ISSUE TITLE
`ds build`: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by varjmes** [entropic-dev/entropic#155]
In the README it says:

> At present, if you want to install packages using ds, you can run ds build in a directory with a Package.toml. This will produce a ds/node_modules directory, which you can move into place by hand. This is a temporary situation!

I attempted `ds build` and found the following issue:

```
~/projects/ent
❯ ds build
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at buildFromMeta (/Users/varjmes/.nvm/versions/node/v12.3.1/lib/node_modules/ds/lib/commands/build.js:120:23)
    at async loadTree (/Users/varjmes/.nvm/versions/node/v12.3.1/lib/node_modules/ds/lib/commands/build.js:44:16)
    at async build (/Users/varjmes/.nvm/versions/node/v12.3.1/lib/node_modules/ds/lib/commands/build.js:30:3)
    at async main (/Users/varjmes/.nvm/versions/node/v12.3.1/lib/node_modules/ds/lib/main.js:39:5)
```

## Steps to replicate

```
mkdir ent
cd ent
```

`Package.toml / package.toml`
```
name = "varjmes@registry.entropic.dev/ent"
version = "2.0.0"
```

`index.js`
```
module.exports = () => {
  console.log('jmes')
}
```

Within this directory

```
ds build
```

Node version: `v12.3.1`
ds version: `v1.0.0`

**Comment by toddself** [comment]
This is because there is no `[dependencies]` stanza in your Package.toml.  PR icoming!

**Comment by varjmes** [comment]
> This is because there is no `[dependencies]` stanza in your Package.toml. PR icoming!

Aha! My challenge for next time is to figure this out myself. Thanks much!

**Comment by toddself** [comment]
oh sorry i hope i didn't jump on it too quick!

`TypeError: Cannot convert undefined or null to object` is the bane of my javascript existence and it's my life's work to eradicate it!

**Comment by varjmes** [comment]
> oh sorry i hope i didn't jump on it too quick!

not at all! :D
