### ISSUE TITLE
Vacation / Out of GitHub Jun 8 - Jun 10

### ISSUE THREAD

**Issue by chrisdickinson** [entropic-dev/entropic#160]
Hey folks! I'm going to try something a bit new. As you know, it's been a really exciting week for Entropic. There've been a _ton_ of great contributions, thank you :heart: Between Entropic and starting a new job, it's been hard to keep up with!

SO! I am going to take a breather this weekend: I'm going to go visit a coastline and not compute for a bit. I wanted to give y'all a heads up for two reasons:

- It may affect you! Expect some delays on PR and issue review, and possibly on my open work (I hope to get #135 done before I leave, but if not, it won't be the end of the world.)
- I want future folks in this role to feel comfortable taking breaks & letting contributors _know_ that they are taking breaks.

In any case, keep up the good work! I'm really happy to see how folks have been interacting here & making the project better. 💞

**Comment by varjmes** [comment]
I'd hoped this would happen, setting an excellent example. Enjoy your break! 🌱

**Comment by joehand** [comment]
> I want future folks in this role to feel comfortable taking breaks & letting contributors know that they are taking breaks.

Great to see this! Thanks for sharing and demonstrating the values you hope to see reflected in this project.

**Comment by chee** [comment]
this is so great <3
have a good computerless

**Comment by chrisdickinson** [comment]
Thanks all! WEEKEND VACATION SUCCESSFULLY VACATED:

![cargo ships](https://user-images.githubusercontent.com/37303/59225872-a9133e80-8b86-11e9-9766-06976110c0d9.jpg)

![town](https://user-images.githubusercontent.com/37303/59225880-b03a4c80-8b86-11e9-95cc-5a2d22f87aa4.jpg)

:heart:
