### ISSUE TITLE
Bulletin: We have a Discourse!

### ISSUE THREAD

**Issue by chrisdickinson** [entropic-dev/entropic#207]
For more info, see here: https://github.com/entropic-dev/entropic/pull/206

It lives at https://discourse.entropic.dev – thanks @ceejbot for setting this up!

**Comment by jacques** [comment]
Thanks @ceejbot!

**Comment by davojta** [comment]
it does n't work right now: 

![image](https://user-images.githubusercontent.com/893650/59151205-b968d380-8a37-11e9-8089-f868f724c278.png)

**Comment by jacques** [comment]
@davojta please confirm if you are still experiencing this issue?

**Comment by davojta** [comment]
@jacques Now everything is working okey

**Comment by zkat** [comment]
I'm using the OpenDNS nameservers, and this is what I get:

<img width="416" alt="Screen Shot 2019-06-12 at 15 12 02" src="https://user-images.githubusercontent.com/17535/59389895-eb4ba400-8d6f-11e9-93e6-063b6e37bdc9.png">

**Comment by chrisdickinson** [comment]
Believe it or not, I might've caused this bug 4 years ago.

(I'm going to close this issue but leave it pinned.)

**Comment by larsgw** [comment]
Hmm, I can't seem to make an account...

> We cannot detect if your account was created, please ensure you have cookies enabled.

**Comment by niklabh** [comment]
Email not coming after signup

**Comment by devsnek** [comment]
not seeing any confirmation email here

**Comment by varjmes** [comment]
Just dropping a note here to say email confirmations are now arriving again. Shout if you have issues.

**Comment by johnmuhl** [comment]
Firefox 67.0.4
Manjaro 18.0.4

(no corporate network/proxy or anti-virus involved)

![image](https://user-images.githubusercontent.com/7944/60596035-c7c3ba00-9d6d-11e9-8d59-39bb7fa28bf2.png)

Chrome connects fine on the same system.

**Comment by neobats** [comment]
Commenting to say that I'm getting the same warning from Firefox today.
