### ISSUE TITLE
Ink for CLI

### ISSUE THREAD

**Issue by olingern** [entropic-dev/entropic#226]
[Ink](https://github.com/vadimdemedes/ink) is a super neat project that allows command line development using React-like components. I think using this _could_ make the CLI more approachable for newcomers as well as providing a nice layer of visual abstraction.

**Comment by zacanger** [comment]
TIL. That looks _so_ cool and I already want to rewrite half of my own projects to use it.

**Comment by olingern** [comment]
It's super interesting. [Yoga layout](https://yogalayout.com/) ( _how Ink positions_ ) turns out to be really useful.

**Comment by chrisdickinson** [comment]
Selfishly, I've been wanting to use this so I'm all for it.

I'd kind of like to see the CLI separate into an API client layer (a la `common/boltzmann/client/index.js`), display layer (in ink, potentially) and dispatch/command layer (what we have now), with our various utility methods getting absorbed into the client or the command layer.

**Comment by emkay** [comment]
Ink looks super rad and I've also been looking for an opportunity to try it out and can help out porting stuff over.

**Comment by boneskull** [comment]
ink is neat but it isn’t without overhead. aside from the tooling, it will incur a noticeable startup penalty. maybe this is the heaviness of React itself—haven’t looked closely at where the bottleneck is.

**Comment by joehand** [comment]
If anyone is interested in alternatives I will plug https://github.com/neat-log/neat-log which we use in the Dat command line. It is still somewhat minimal but I would love any critical but kind eyes on it.  I have also been eyeing Ink but have yet to compare more in depth...

Folks have written a chat client with it and mostly works =) https://github.com/cabal-club/cabal#cabal-cli

**Comment by MichaelDimmitt** [comment]
Another alternative: [oclif](https://oclif.io/)

**Comment by ChrisBrownie55** [comment]
@boneskull If the bottleneck is in React itself, I wonder if it would be viable to use Preact in its place?

**Comment by boneskull** [comment]
@ChrisBrownie55 I don't think so.  Ink uses [yoga](https://github.com/facebook/yoga); preact does not.

**Comment by ChrisBrownie55** [comment]
@boneskull I was referring to using Preact in place of React, this would still be in conjunction with Ink. But I've tried to test using `preact/compat` by aliasing `react` to it but it would appear that Ink relies too heavily on the internal systems/variables of React making impossible to just switch to Preact.

**Comment by wardpeet** [comment]
You should take a look at [pasterl](https://github.com/vadimdemedes/pastel). It uses ink under the hood but is a replacement for things like yargs, meow, ...
