### ISSUE TITLE
CLI cannot reach registry

### ISSUE THREAD

**Issue by olingern** [entropic-dev/entropic#228]
# Is this a feature request or a bug?
Bug
![DeepinScreenshot_select-area_20190610121907](https://user-images.githubusercontent.com/1470297/59170638-84b16500-8b7a-11e9-81cc-707951842b08.png)

# Expected behavior:
CLI can reach registry.entropic.dev

# Actual behavior:
Failing due to registry not having a IPv6 record

See:
https://ready.chair6.net/?url=https%3A%2F%2Fregistry.entropic.dev

# Proposal
Revert #177
Close #183 

After revert:

![DeepinScreenshot_select-area_20190610123849](https://user-images.githubusercontent.com/1470297/59171182-d1963b00-8b7c-11e9-9e94-d76e1a1bd057.png)

# Steps to replicate:
1. cd `cli`
2. `node ./lib/main.js whoami`

# Environment info
- OS: Arch Linux x86_64
- Version of Node:  `12.3.0`
- Version of ds: `master` branch

**Comment by niklabh** [comment]
this is working with node  version 12.5.0

**Comment by olingern** [comment]
I think other people had ( still have? ) this issue. Not really a Node specific issue as much it is an IP address issue
