### ISSUE TITLE
Lo-fi web mockups

### ISSUE THREAD

**Issue by olingern** [entropic-dev/entropic#240]
## Description

I thought it could be interesting to throw together some low-fi, _mostly_ grayscale mockups to get an idea of what's required for someone to start on #107 

Questions:
- Do people find these helpful for talking points?
- What pages do we actually need? Just a handful off the top of my head.
  - Home
  - Search
  - Search results
  - Package page
  - User page
- Move this to [discourse](https://discourse.entropic.dev/)?

**DISCLAIMER: I am by no means a designer!**

### Homepage
Kind of tricky because anyone can run their own instance. Maybe this isn't really applicable and their needs to be a "meta" site that actually tells people what entropic is. Maybe [what Arch does](https://aur.archlinux.org/) is more applicable than [what npm does](https://www.npmjs.com/).

___

_A bit hard to see here on Github. Illustration is just placeholder from [Zabombey on Dribble](https://dribbble.com/shots/4606457-Modum-Packaging)_

![home](https://user-images.githubusercontent.com/1470297/59202811-3c289480-8bd8-11e9-9daf-c58d61e74c13.png)

### Package page
Missing a lot of metrics, namespace, etc. Just to kind of get things started.

![package](https://user-images.githubusercontent.com/1470297/59203093-dab4f580-8bd8-11e9-9dc2-7e434ee3ad3d.png)

**Comment by enykeev** [comment]
> Kind of tricky because anyone can run their own instance. Maybe this isn't really applicable and their needs to be a "meta" site that actually tells people what entropic is. Maybe what Arch does is more applicable than what npm does.

As I see it, there needs to be two sites: one for Entropic as an application that tells the story and serves as a landing page and another one for registry instance (doesn't really matter whether official or local or however the language goes).

Your first mockup is an example of the Entropic as application. It tells a story, it has a call for action, it's here to capture attention and answer basic questions for the newcomer. This website needs to have a link to documentation (or it being a part of this site), a link to discourse, to github. It should provide an information of what Entropic is, give clear instructions of how to use, how to setup your own repo, where to ask questions and how to contribute.

The second mockup is an example of the page users will likely see most often when they stumble upon Entropic by accident while looking for a particular library to solve their problem. This page on the other hand, should be a part of repository UI. This website should give you a view into what particular repo contains (a list, a search, a top, however you cut it). It should also give you ability to authenticate, manage your packages and settings (which right now is only auth tokens, as far as I'm aware).

Both pages should link to each other when reasonable. The Entropic page should link to official repo (once again I'm not clear on whether "official" is even the right term here) and repo page should link to Entropic for basic information on how to use it.

**Comment by enykeev** [comment]
And also, I'm not affiliated with them in any way, but back on my previous job we had pretty decent experience using InVision for rapid back and forth on UI/UX so if you ever feel constrained by mocks in github issues, I suggest giving it a shot.

**Comment by olingern** [comment]
> As I see it, there needs to be two sites: one for Entropic as an application that tells the story and serves as a landing page and another one for registry instance

:+1:  This is exactly what I was thinking

> experience using InVision for rapid back and forth on UI/UX 

I'm a _very_ light user of [Figma](https://www.figma.com/files/recent), but am open to whatever will help us reason about building things out. Also, if there are any other designers wanting to jump in, please do!

**Comment by varjmes** [comment]
An unexpected request to be sure, but could we not use left-pad as our example? To my understanding the left-pad event was quite a stressful event for those who work (and still work) at npm, some of those are contributing to this repo in earnest or have the desire to. Let's use a different package in our mockups 🧡

Excited to see this get going!

**Comment by olingern** [comment]
I can do that. I wasn't really privy to the internals of how this went at npm, but I can see how it was stressful. Because it's so _infamous_, I just kind of see `left-pad` for packages as `foo bar baz` is for variables.

**Comment by enykeev** [comment]
> Maybe what Arch does is more applicable than what npm does.

Seems like npm suddenly decided to do something else between original post and now. Just wanna make sure the sentence still means what it meant yesterday.

**Comment by ztolley** [comment]
Definitely need a getting started tldr in the GitHub readme or the site to come. The idea is exciting but hard to grasp when all you know is npm

**Comment by zacanger** [comment]
@ztolley I think [this one](https://github.com/entropic-dev/entropic/blob/master/docs/README.md) is a good place to start, but unless you know what you're looking for it's hard to find right now.

**Comment by mannyluvstacos** [comment]
Thank you for this read @zacanger!

I appreciate the context that document provides and it has me excited and curious to know (and be a part of writing) what goes in the blanks!😊
