### ISSUE TITLE
Private packages?

### ISSUE THREAD

**Issue by fetis** [entropic-dev/entropic#244]
# Is this a feature request or a bug?
feature request

Current manifest https://github.com/entropic-dev/entropic/tree/master/docs#assumptions--decisions--the-chem-in-the-golems-head
says that 
> All packages are public.

how does this correlate to the problem: I want to publish private packages, only for my company, for example. Even if we host registry internally, for example. Is it temporary to make "dumbest thing possible" or private packages never will be supported by entropic?

**Comment by ChrisCallanJr** [comment]
Not a maintainer of this, but I believe this is covered in the Overview section of the readme:

> All packages published to Entropic are public. Our expectation is that you'll use something like the GitHub Package Registry if you need to control access to packages you publish. Or you might choose to run an Entropic instance and control access to it another way.

**Comment by chrisdickinson** [comment]
Yep, what @ChrisCallanJr said. In particular, our current thinking is that you can run an Entropic inside your private network and publish packages to it – these packages will not be visible to the outside world, won't be federated, & thus are effectively "private."

**Comment by fetis** [comment]
will this private installation communicate with outer world to mirror public packages or it'll hold only private ones?

**Comment by ChrisCallanJr** [comment]
@fetis by my admittedly limited understanding of federated systems, an instance of Entropic in a private network would be outside of the federated system and cut off from other instances. I imagine practices will emerge in which you'll have a _namespace_ instance for public packages and a _namespace-private_ instance for all of your private paackages

**Comment by fetis** [comment]
> I imagine practices will emerge in which you'll have a namespace instance for public packages

@ChrisCallanJr but it doesn't sound like I _have to_ have this instance. I still can use the public one. Similar like we do nowadays. You can use npm registry for public packages and jFrog Aritfactory (or GitHub registry or anything else) for private only.

**Comment by ChrisCallanJr** [comment]
@fetis exactly. I was moreso suggesting a practice if you chose to use entropic exclusively for package management 😃
