### ISSUE TITLE
P2P, Blockchain & Alternative decentralization systems

### ISSUE THREAD

**Issue by philippefutureboy** [entropic-dev/entropic#252]
# Is this a feature request or a bug?

A discussion, quick suggestion :)

# What do you want to talk about?

Alternative protocols & platforms to support a decentralized ecosystem.

_Disclaimer: I do not have any experience in decentralized systems_

# So?

Have you considered using P2P protocols?

What about having a system like the IPFS or Skycoin for distributed data? The advantages I would see in using a blockchain solution is that you can offer both package signing and have a commonly agreed package history stored in the blockchain that is immutable.

What do you think? If you'd like I can see if I can grab a few experts in P2P/Blockchain/decentralized systems and invite them to join the discussion :)

Thank you for your initiative.

🚀

**Comment by superhawk610** [comment]
IPFS came up in a discussion a couple days ago, let me see if I can find it...

**Comment by wesleytodd** [comment]
Might be worth checking out [Dat](https://dat.foundation/).  It is "js native" and has a relatively thriving, if still small, maintainer/user base.

**Comment by philippefutureboy** [comment]
@wesleytodd Dat was already proposed in #99, but one of the contributors of Dat said that Dat may not be a good fit for this type of application.

**Comment by wesleytodd** [comment]
My edit must have been after you posted.  Sorry I had noticed that right after posting.  Might be a good idea to close this issue so others don't make the same mistake as I?

**Comment by philippefutureboy** [comment]
Good point => Closing.
