### ISSUE TITLE
Question: Tools for version management GitLab, GitHub, Bitbucket ... etc.

### ISSUE THREAD

**Issue by MichaelDimmitt** [entropic-dev/entropic#289]
## Question/Feature Request
Thinking about the problem of allowing more registries.

Anyone know a Cli's which automatically create version numbers for projects with git/svn/other remotes? It does not seem difficult but a matter of someone who put in the time to contact the Api's: GitLab, GitHub ... etc.

Maybe there is a github awesome that lists a bunch of them?

Meaning when you run hypothetical "remote-publish" it will check your Package file for the version number of your project and make a /Put to update the remote location such as GitLab to create a new version.

If the /Put request fails then the `ds publish` command could fail and require users to upgrade their version number in the Package file.

## Posible wrapper in bash for adding a package check to 'ds'
```bash
ds(){ 
  remote-publish $(git remote get-url origin) && 
  $(which ds) $* $H ||
  echo 'Upgrade version in Package file to publish';
};
```

Related to #142, #141

Hope this communication makes sense. 
If this does not seem helpful feel free to close the issue.
Some of the communication in the project has gone over my head.

Happy to communicate further for clarity.

**Comment by MichaelDimmitt** [comment]
Note: this might not be a problem entropic is trying to solve. People can manage their versions manually. However, I have found that development is more seamless when the 'Package file' synced up with the Repository.

**Comment by zacanger** [comment]
I'm a little confused about what you're asking, are you looking for something like `npm version` or [`cargo bump`](https://github.com/wraithan/cargo-bump) followed by `git push --follow-tags`?

**Comment by MichaelDimmitt** [comment]
@zacanger, `git push --follow-tags` was exactly what I was looking for.
This would solve the problem for Github, Gitlab, and Bitbucket. 👍

https://gist.github.com/DarrenN/8c6a5b969481725a4413#gistcomment-1694379
```bash

git tag $(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]') && git push --tags

```
If a command like this was built into `ds publish` as a pre-publish instead of a post-publish it could help to determine whether a package has been published to a registry.

But maybe this is a bad idea because it may make sense to publish a package with the same version to multiple registries.

Anyway thanks for the comment. 
I did not know about the `git push --follow-tags` command.
I Learned something new today. 🎉
