### ISSUE TITLE
Docker Hub builds

### ISSUE THREAD

**Issue by zacanger** [entropic-dev/entropic#291]
# Is this a feature request or a bug?

Feature request

# Expected behavior:

Commits to master and git tags build and push images to [Docker Hub](hub.docker.com/u/entropicdev) (see also [this script](https://github.com/entropic-dev/entropic/blob/master/misc/build-images.sh)).

# Actual behavior:

I've been doing it manually from my machine.

# Details

Images could be built and pushed in Circle, but that could lead to [credentials leaking](https://github.com/entropic-dev/entropic/issues/281#issuecomment-504120966). I wonder if [automated builds](https://docs.docker.com/docker-hub/builds/) would be better? That would probably require a service account or one of the maintainers or moderators setting it up.

**Comment by veera83372** [comment]
Hey, I am curious to understand, how publishing images from `Circle CI`   could lead to `credentials leaking`.

**Comment by zacanger** [comment]
Docker Cloud credentials would have to be made available as environment variables to the build. If someone were to get in some malicious code, they could steal those credentials and have access to hub.docker.com/u/entropicdev.

**Comment by veera83372** [comment]
My understanding is that `CI tools` make secure env variables available for an only master/development branch. In that case, the malicious code should be merged to master, That won't happen very easily because there will be multiple reviews for each PR.
