### ISSUE TITLE
Terraform setup

### ISSUE THREAD

**Issue by zacanger** [entropic-dev/entropic#294]
# Is this a feature request or a bug?

Feature request

# Details

It might be nice to have a Terraform story for folks who aren't using Docker or Kubernetes. Kubernetes should be mostly solved if #204 lands, but there are likely folks who aren't willing to set up a cluster, figure out how they want to manage it, etc.

Having a Terraform setup that works with at least AWS might not be bad (and maybe a prioritized list of platforms folks could add, with issues folks could claim). I would not be able to work on this, my Terraforming is rudimentary (I can apply it and fix issues, but that's about it), just throwing it out there as an idea.

At minimum, this would probably need to provision machines for each of the services (registry, storage, and web, currently), add Node, set up Postgres and Redis (RDS + ElastiCache, Cloud SQL + Memorystore, etc.), get everything connected (env vars), set up networking (expose the right ports on the right services), and possibly have options for DNS.

**Comment by jdbohrman** [comment]
Hey I'd love to help out on this!

**Comment by veera83372** [comment]
Hey, I am also happy to involve in this, As I am currently working on infra automation in my day job

**Comment by chrisdickinson** [comment]
I'm a big fan of terraform, so I'd love to see this!

**Comment by zxaos** [comment]
Would the general preference here be to prefer to just throw a bunch of docker containers on the provider to make it more cloud-agnostic, or would we rather prefer cloud-provider-managed resources? (i.e. for AWS, postgres on RDS or on elastic beanstalk or an ec2 instance?)

**Comment by zacanger** [comment]
I think using managed resources would be a good idea. If someone just wants to throw a bunch of containers up, they could use the [k8s setup](https://github.com/entropic-dev/entropic/blob/master/misc/k8s/README.md) with managed k8s or minikube. Just my opinion, though.

**Comment by mannyluvstacos** [comment]
Is this task/issue already spoken for and currently being worked on?
cc: @chrisdickinson, @zacanger, @ceejbot, @zkat 

@flyinprogrammer and I would love to pair and take on this task/issue.

flyinprogrammer (Alan) has experience in terraform and offered to pair with me on this so that knowledge gets shared and I level up my experience with terraform.

**Comment by mannyluvstacos** [comment]
Hi @zxaos!

@chrisdickinson suggested on the discourse to check in with you about this task and its current state.
Is this currently being worked on? If it is still available, @flyinprogrammer and myself would love to pair up on this.

**Comment by zacanger** [comment]
@mannyluvstacos a couple people have expressed interest in working on it, but no one's claimed it yet, so I think you can go for it!

**Comment by mannyluvstacos** [comment]
@zacanger thank you for the quick reply!
Understood!

**Comment by mannyluvstacos** [comment]
This is a restatement of @zacanger ideas into checkbox/bullet form for AC and clear expectations:

At minimum, this would probably 
- [ ] need to provision machines for each of the services 
     - [ ] registry
     - [ ] storage
     - [ ] and web
     - [ ] add Node
- [ ] set up Postgres
- [ ] set up Redis (
	- [ ] RDS + ElastiCache
 	- [ ] Cloud SQL + Memorystore
- [ ] get everything connected (env vars)
- [ ] set up networking 
	- [ ] (expose the right ports on the right services)
- [ ] possibly have options for DNS

**Comment by zacanger** [comment]
I'm going to close this since there's now [a repo](https://github.com/entropic-dev/terraform-aws-entropic/) for it.
