### ISSUE TITLE
Document .env files needed for `docker-compose start`

### ISSUE THREAD

**Issue by smikes** [entropic-dev/entropic#295]
# Is this a feature request or a bug?
Documentation bug

# Expected behavior:
docker-compose start
-> running registry

# Actual behavior:
Environment files need to be created first:
```
Svarog:entropic smikes$ touch ./services/registry/.env
Svarog:entropic smikes$ touch ./services/web/.env
Svarog:entropic smikes$ touch ./services/storage/.env
```

# Steps to replicate:
Clone repo, attempt to start registry with `docker-compose start`

**Comment by zacanger** [comment]
That's documented [here](https://github.com/entropic-dev/entropic/blob/master/docs/HACKING.md#running-services), but maybe needs to be more obvious.

**Comment by smikes** [comment]
Thanks.
