### ISSUE TITLE
Two `docs/rfcs` directories

### ISSUE THREAD

**Issue by zacanger** [entropic-dev/entropic#307]
# Is this a feature request or a bug?

Bug

# Expected behavior:

Only one RFC directory

# Actual behavior:

There are two!

# Steps to replicate:

`ls docs`

I'm guessing this is because some folks are on Macs. FWIW I like to enforce all `lisp-case` directory and filenames at $dayjob (except for README.md and LICENSE.md) for exactly that reason, because dealing with case insensitive/case preserving but insensitive/case sensitive filesystem issues is just a headache when it happens.

Currently this will cause issues for anyone who tries to pull from master on Linux.

# Environment info (where relevant)

- Browser: N/A
- Operating System & Version: macOS and Ubuntu 18
- Version of Node (`node -v`): N/A
- Version of ds (`ds --version`): N/A

**Comment by chrisdickinson** [comment]
Sorry about this! This should be fixed as of 79e9294.

**Comment by zacanger** [comment]
Thanks!
